import type { Import } from '../../../../shared/types.ts'

const pythonBuiltins = new Set([
    '_abc',
    '_ast',
    '_bisect',
    '_blake2',
    '_codecs',
    '_codecs_cn',
    '_codecs_hk',
    '_codecs_iso2022',
    '_codecs_jp',
    '_codecs_kr',
    '_codecs_tw',
    '_collections',
    '_contextvars',
    '_csv',
    '_datetime',
    '_functools',
    '_heapq',
    '_hmac',
    '_imp',
    '_interpchannels',
    '_interpqueues',
    '_interpreters',
    '_io',
    '_json',
    '_locale',
    '_lsprof',
    '_md5',
    '_multibytecodec',
    '_opcode',
    '_operator',
    '_pickle',
    '_random',
    '_sha1',
    '_sha2',
    '_sha3',
    '_signal',
    '_sre',
    '_stat',
    '_statistics',
    '_string',
    '_struct',
    '_suggestions',
    '_symtable',
    '_sysconfig',
    '_thread',
    '_tokenize',
    '_tracemalloc',
    '_types',
    '_typing',
    '_warnings',
    '_weakref',
    '_winapi',
    'array',
    'atexit',
    'binascii',
    'builtins',
    'cmath',
    'errno',
    'faulthandler',
    'gc',
    'itertools',
    'marshal',
    'math',
    'mmap',
    'msvcrt',
    'nt',
    'sys',
    'time',
    'winreg',
    'xxsubtype',
    'zlib',
    'binascii',
    'contextvars',
    'numbers',
    'signal',
    '_csv',
    '_queue',
    'readline',
    '_posixsubprocess',
    'zoneinfo',
    'wsgiref',
    '_weakref',
    'sqlite3',
    'pprint',
    '_bisect',
    'bz2',
    'platform',
    'winsound',
    '_random',
    'functools',
    'logging',
    'types',
    'heapq',
    'io',
    'shlex',
    'tokenize',
    '_posixshmem',
    'difflib',
    '_codecs_iso2022',
    'struct',
    'tarfile',
    'pkgutil',
    'sre_parse',
    'termios',
    '_sha3',
    'annotationlib',
    'tty',
    'tkinter',
    '_scproxy',
    '_codecs_kr',
    '_pyrepl',
    'queue',
    '_curses',
    '_hmac',
    '_suggestions',
    '_io',
    '_sre',
    'copyreg',
    'stringprep',
    'antigravity',
    'winreg',
    '_pylong',
    'sched',
    'ftplib',
    '_types',
    '_sqlite3',
    '_statistics',
    '_tokenize',
    'grp',
    'calendar',
    'marshal',
    'opcode',
    '_multibytecodec',
    'errno',
    'hashlib',
    'optparse',
    'pyclbr',
    '_compat_pickle',
    'abc',
    'copy',
    'pickle',
    'pstats',
    'compileall',
    'statistics',
    'sre_constants',
    'posixpath',
    '_typing',
    '_operator',
    '_apple_support',
    'colorsys',
    '_ast',
    'multiprocessing',
    'rlcompleter',
    'select',
    'cProfile',
    'curses',
    'zlib',
    'modulefinder',
    'idlelib',
    '_functools',
    'mimetypes',
    'mmap',
    '_interpchannels',
    '_zstd',
    'trace',
    'webbrowser',
    'getpass',
    '_string',
    '_tkinter',
    '_pyio',
    'bisect',
    'wave',
    'weakref',
    'pydoc_data',
    'pyexpat',
    '_lzma',
    'tabnanny',
    '_osx_support',
    'zipimport',
    '_struct',
    '_sha1',
    'code',
    '_py_abc',
    'textwrap',
    'uuid',
    'zipapp',
    'gc',
    '_pydatetime',
    '_stat',
    're',
    'http',
    'shutil',
    'mailbox',
    'poplib',
    'os',
    'contextlib',
    'quopri',
    'imaplib',
    'codecs',
    '_zoneinfo',
    '_socket',
    '_sysconfig',
    'dbm',
    'genericpath',
    'this',
    'asyncio',
    '_hashlib',
    '_elementtree',
    '_datetime',
    'bdb',
    'pathlib',
    'pdb',
    'shelve',
    '_aix_support',
    'email',
    '_threading_local',
    'argparse',
    'faulthandler',
    'math',
    'sysconfig',
    '_collections_abc',
    'secrets',
    'gettext',
    'resource',
    'tomllib',
    'inspect',
    '_multiprocessing',
    'msvcrt',
    'sys',
    'encodings',
    'base64',
    'itertools',
    'tempfile',
    'venv',
    'xmlrpc',
    'fnmatch',
    'timeit',
    '_ast_unparse',
    'compression',
    'configparser',
    'syslog',
    'keyword',
    'subprocess',
    'pty',
    'selectors',
    'tracemalloc',
    'decimal',
    '_codecs_tw',
    '_remote_debugging',
    'pwd',
    '_asyncio',
    'fcntl',
    'datetime',
    'runpy',
    'smtplib',
    '_locale',
    '_interpreters',
    'socket',
    '_bz2',
    'concurrent',
    'stat',
    'locale',
    '_codecs_cn',
    'turtle',
    'graphlib',
    'fileinput',
    'turtledemo',
    'dataclasses',
    'profile',
    '_abc',
    '_imp',
    '_pickle',
    '_codecs',
    '_strptime',
    '_symtable',
    'gzip',
    '_markupbase',
    '_signal',
    'ipaddress',
    '_warnings',
    'socketserver',
    '__future__',
    '_interpqueues',
    'codeop',
    'symtable',
    'string',
    '_sha2',
    '_android_support',
    '_ctypes',
    '_weakrefset',
    'enum',
    'traceback',
    'xml',
    'zipfile',
    'array',
    'random',
    'netrc',
    '_opcode',
    '_py_warnings',
    '_uuid',
    'ntpath',
    '_ssl',
    '_codecs_jp',
    '_opcode_metadata',
    'urllib',
    'csv',
    '_frozen_importlib_external',
    'pickletools',
    '_md5',
    '_curses_panel',
    '_decimal',
    '_heapq',
    'ensurepip',
    '_collections',
    'fractions',
    'nturl2path',
    '_codecs_hk',
    'unittest',
    'reprlib',
    '_thread',
    '_ios_support',
    '_lsprof',
    'typing',
    'atexit',
    'json',
    '_overlapped',
    'glob',
    'doctest',
    'filecmp',
    'hmac',
    '_dbm',
    '_wmi',
    'ssl',
    'linecache',
    '_tracemalloc',
    '_gdbm',
    'ast',
    '_json',
    '_colorize',
    'cmath',
    'getopt',
    '_blake2',
    '_winapi',
    'collections',
    'importlib',
    'posix',
    'site',
    '_contextvars',
    'operator',
    'sre_compile',
    'token',
    'ctypes',
    'cmd',
    'dis',
    'plistlib',
    'warnings',
    '_frozen_importlib',
    'lzma',
    'builtins',
    'html',
    'nt',
    '_pydecimal',
    'pydoc',
    'threading',
    'time',
    'unicodedata',
    'py_compile',
    '_sitebuiltins',
])

function classifyImport(moduleName: string): Import {
    const label = moduleName.trim()
    if (label.startsWith('.')) return { type: 'file', label }

    const root = label.split('.')[0] ?? label
    return pythonBuiltins.has(root)
        ? { type: 'lib-builtin', label: root }
        : { type: 'lib-external', label }
}

export function parsePython(code: string): Import[] {
    const imports: Import[] = []
    const statements: string[] = []
    let statement = ''
    let bracketDepth = 0

    for (const line of code.split(/\r?\n/)) {
        const withoutComment = line.replace(/\s+#.*$/, '').trim()
        if (!withoutComment && !statement) continue
        statement += `${statement ? ' ' : ''}${withoutComment.replace(/\\$/, '').trim()}`
        bracketDepth +=
            (withoutComment.match(/[([{]/g)?.length ?? 0) -
            (withoutComment.match(/[)\]}]/g)?.length ?? 0)
        if (bracketDepth > 0 || withoutComment.endsWith('\\')) continue
        if (statement) statements.push(statement)
        statement = ''
        bracketDepth = 0
    }
    if (statement) statements.push(statement)

    for (const importStatement of statements) {
        const importMatch = importStatement.match(/^import\s+(.+)$/)
        if (importMatch?.[1]) {
            for (const item of importMatch[1].replace(/^\(|\)$/g, '').split(',')) {
                const moduleName = item.trim().split(/\s+as\s+/)[0]
                if (moduleName) imports.push(classifyImport(moduleName))
            }
            continue
        }

        const fromMatch = importStatement.match(/^from\s+([\w.]+)\s+import\s+(.+)$/)
        if (!fromMatch?.[1]) continue

        const moduleName = fromMatch[1]
        if (/^\.+$/.test(moduleName) && fromMatch[2]) {
            for (const item of fromMatch[2].replace(/^\(|\)$/g, '').split(',')) {
                const importedName = item.trim().split(/\s+as\s+/)[0]
                if (importedName && importedName !== '*') {
                    imports.push({ type: 'file', label: `${moduleName}${importedName}` })
                }
            }
        } else {
            imports.push(classifyImport(moduleName))
        }
    }

    return [
        ...new Map(
            imports.map((imported) => [`${imported.type}:${imported.label}`, imported]),
        ).values(),
    ]
}

export default parsePython
